development:
  access_key_id: 'AKIAI5NICTEIB34OL7WA'
  secret_access_key: 'LBDrBnFm+us1dx7/ix22QbIYYjxJxLWR88vgK3O2'
  persistent: true
  # bucket: YOUR BUCKET
  max_file_size: 10485760
  # acl: public-read